In [1]:

import numpy as np 
import pandas as pd 
import nibabel as nib
import os
from nilearn import image, plotting

import kagglehub


img = nib.load('/kaggle/input/competitions/ehl-paris-medical-image-retrieval/dataset1/images/test/gallery/g_027adec2ca24.nii')

data = img.get_fdata()             # tableau numpy (3D ou 4D)
print(data.shape)
print(img.affine)                  # matrice de transformation spatiale
print(img.header)                  # en-tête NIfTI

#for dirname, _, filenames in os.walk('/kaggle/input/competitions/ehl-paris-medical-image-retrieval/dataset1/images/test/gallery'):
#    for filename in filenames:
#        print(os.path.join(dirname, filename))



(240, 240, 155)
[[   1.    0.   -0. -239.]
 [   0.    1.   -0.   -0.]
 [   0.    0.    1.    0.]
 [   0.    0.    0.    1.]]
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 240 240 155   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1. 1. 1. 1. 0. 0. 0. 0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 